apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ytfu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ytfu
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ytfu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ytfu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ytfu
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-cdfd-tenant/rhtap-demo-app/hacbs-test-project-ytfu@sha256:d895dc194ff6fc6334fd9dfcde991f2fab9727d1276f1db587a4f2516402cba6
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
